allowBuilds:
  esbuild: true
  vue-demi: true

overrides:
  js-cookie: 3.0.7
  form-data@<4.0.6: ">=4.0.6"
  postcss@<8.5.18: ">=8.5.18"
  dompurify@<3.4.14: ">=3.4.14"
  yaml@1.10.2: 1.10.3
  uuid@11.1.0: 11.1.1
  uuid@13.0.0: 13.0.1
  mermaid@11.14.0: 11.16.1
  decode-uri-component@0.4.1: 0.5.0
