package service

import (
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

// openAIOutboundPromptCacheKeyPrefix identifies keys generated by this gateway.
// It also lets later WS frames preserve a server-derived key when they omit the
// stable prefix fields that were present on response.create.
// 注意：前缀必须是中性字符串，不得包含网关/产品名称——该值会原样发往上游。
const (
	openAIOutboundPromptCacheKeyPrefix      = "pcv2-"
	openAIOutboundPromptCacheKeyMaxLength   = 64
	openAIOutboundPromptCacheKeyDigestBytes = sha256.Size
)

func encodeOpenAIOutboundPromptCacheKey(sum [sha256.Size]byte) string {
	return openAIOutboundPromptCacheKeyPrefix + base64.RawURLEncoding.EncodeToString(sum[:])
}

// deriveOpenAIOutboundPromptCacheKey creates the only prompt_cache_key allowed
// to leave the gateway. It is intentionally independent of account IDs, API
// key IDs, device IDs, session/thread/turn IDs, and client-provided keys.
func deriveOpenAIOutboundPromptCacheKey(body []byte, mappedModel string) string {
	return deriveOpenAIOutboundPromptCacheKeyByPolicy(body, mappedModel, false)
}

// deriveOpenAIOutboundPromptCacheKeyForSession requires a conversation anchor.
// It is used by native Codex subscription traffic so a shared tools/instructions
// prefix cannot collapse unrelated sessions into one cache partition.
func deriveOpenAIOutboundPromptCacheKeyForSession(body []byte, mappedModel string) string {
	return deriveOpenAIOutboundPromptCacheKeyByPolicy(body, mappedModel, true)
}

func deriveOpenAIOutboundPromptCacheKeyByPolicy(body []byte, mappedModel string, requireSessionAnchor bool) string {
	if len(body) == 0 {
		return ""
	}

	model := strings.TrimSpace(mappedModel)
	if model == "" {
		model = strings.TrimSpace(gjson.GetBytes(body, "model").String())
	}
	model = normalizeCodexModel(model)
	if model == "" {
		return ""
	}

	seed := ""
	if !requireSessionAnchor {
		seed = strings.TrimSpace(deriveOpenAIStablePrefixSessionSeed(body))
	}
	if seed == "" {
		seed = strings.TrimSpace(deriveOpenAIAnchoredContentSessionSeed(body))
	}
	if seed == "" {
		return ""
	}

	sum := sha256.Sum256([]byte(fmt.Sprintf(
		"sub2api:openai-prompt-cache:v2\nmodel=%s\nseed=%s",
		model,
		seed,
	)))
	return encodeOpenAIOutboundPromptCacheKey(sum)
}

func deriveOpenAIOutboundPromptCacheKeyFromClientKey(clientKey, mappedModel string) string {
	clientKey = strings.TrimSpace(clientKey)
	if clientKey == "" {
		return ""
	}

	model := normalizeCodexModel(mappedModel)
	sum := sha256.Sum256([]byte(fmt.Sprintf(
		"sub2api:openai-prompt-cache:v2\nmodel=%s\nclient-key=%s",
		model,
		clientKey,
	)))
	return encodeOpenAIOutboundPromptCacheKey(sum)
}

func deriveOpenAIOutboundPromptCacheKeyFallback(clientKey, mappedModel string) string {
	clientKey = strings.TrimSpace(clientKey)
	if clientKey == "" {
		return ""
	}
	if isGatewayPromptCacheKeyValue(clientKey) {
		return clientKey
	}
	return deriveOpenAIOutboundPromptCacheKeyFromClientKey(clientKey, mappedModel)
}

// rewriteOpenAIOutboundPromptCacheKey removes any client key and replaces it
// with a stable gateway-derived key. A previously generated gateway key is
// preserved on follow-up frames. When a later request only carries the
// client-provided key, derive from that opaque local affinity input instead of
// deleting the key and losing cache continuity.
func rewriteOpenAIOutboundPromptCacheKey(body []byte, mappedModel string) ([]byte, string, error) {
	return rewriteOpenAIOutboundPromptCacheKeyByPolicy(body, mappedModel, false)
}

func rewriteOpenAIOutboundPromptCacheKeyForSession(body []byte, mappedModel string) ([]byte, string, error) {
	return rewriteOpenAIOutboundPromptCacheKeyByPolicy(body, mappedModel, true)
}

func rewriteOpenAIOutboundPromptCacheKeyByPolicy(
	body []byte,
	mappedModel string,
	requireSessionAnchor bool,
) ([]byte, string, error) {
	if len(body) == 0 {
		return body, "", nil
	}

	existing := strings.TrimSpace(gjson.GetBytes(body, "prompt_cache_key").String())
	if isGatewayPromptCacheKeyValue(existing) {
		return body, existing, nil
	}

	derived := ""
	if existing != "" {
		derived = deriveOpenAIOutboundPromptCacheKeyFallback(existing, mappedModel)
	}
	if derived == "" {
		derived = deriveOpenAIOutboundPromptCacheKeyByPolicy(body, mappedModel, requireSessionAnchor)
	}
	if derived == "" {
		if !gjson.GetBytes(body, "prompt_cache_key").Exists() {
			return body, "", nil
		}
		removed, err := sjson.DeleteBytes(append([]byte(nil), body...), "prompt_cache_key")
		if err != nil {
			return body, "", fmt.Errorf("remove client prompt cache key: %w", err)
		}
		return removed, "", nil
	}

	rewritten, err := sjson.SetBytes(append([]byte(nil), body...), "prompt_cache_key", derived)
	if err != nil {
		return body, "", fmt.Errorf("set derived prompt cache key: %w", err)
	}
	return rewritten, derived, nil
}

// rewriteOpenAIOutboundPromptCacheKeyWithFallback preserves a gateway-derived
// key across follow-up frames that omit prompt_cache_key. The fallback is
// injected into a copy of the payload, so callers retain ownership of their
// original request body for retries and account failover.
func rewriteOpenAIOutboundPromptCacheKeyWithFallback(body []byte, mappedModel, fallbackKey string) ([]byte, string, error) {
	return rewriteOpenAIOutboundPromptCacheKeyWithFallbackByPolicy(body, mappedModel, fallbackKey, false)
}

func rewriteOpenAIOutboundPromptCacheKeyWithSessionFallback(
	body []byte,
	mappedModel string,
	fallbackKey string,
) ([]byte, string, error) {
	return rewriteOpenAIOutboundPromptCacheKeyWithFallbackByPolicy(body, mappedModel, fallbackKey, true)
}

func rewriteOpenAIOutboundPromptCacheKeyWithFallbackByPolicy(
	body []byte,
	mappedModel string,
	fallbackKey string,
	requireSessionAnchor bool,
) ([]byte, string, error) {
	fallbackKey = strings.TrimSpace(fallbackKey)
	if fallbackKey != "" &&
		isGatewayPromptCacheKeyValue(fallbackKey) &&
		strings.TrimSpace(gjson.GetBytes(body, "prompt_cache_key").String()) == "" {
		injected, err := sjson.SetBytes(append([]byte(nil), body...), "prompt_cache_key", fallbackKey)
		if err != nil {
			return body, "", fmt.Errorf("inject fallback prompt cache key: %w", err)
		}
		body = injected
	}
	return rewriteOpenAIOutboundPromptCacheKeyByPolicy(body, mappedModel, requireSessionAnchor)
}

// rewriteOpenAIOutboundPromptCacheKeyMap is the map equivalent used by the
// Responses WebSocket payload path.
func rewriteOpenAIOutboundPromptCacheKeyMap(payload map[string]any, mappedModel string) (string, error) {
	if payload == nil {
		return "", nil
	}
	raw, err := json.Marshal(payload)
	if err != nil {
		return "", fmt.Errorf("marshal websocket payload for prompt cache key: %w", err)
	}
	rewritten, key, err := rewriteOpenAIOutboundPromptCacheKey(raw, mappedModel)
	if err != nil {
		return "", err
	}
	if string(rewritten) == string(raw) {
		return key, nil
	}
	var updated map[string]any
	if err := json.Unmarshal(rewritten, &updated); err != nil {
		return "", fmt.Errorf("unmarshal websocket payload after prompt cache key rewrite: %w", err)
	}
	for name := range payload {
		delete(payload, name)
	}
	for name, value := range updated {
		payload[name] = value
	}
	return key, nil
}

func rewriteOpenAIOutboundPromptCacheKeyMapWithFallback(payload map[string]any, mappedModel, fallbackKey string) (string, error) {
	if payload == nil {
		return "", nil
	}
	raw, err := json.Marshal(payload)
	if err != nil {
		return "", fmt.Errorf("marshal websocket payload for prompt cache key fallback: %w", err)
	}
	rewritten, key, err := rewriteOpenAIOutboundPromptCacheKeyWithSessionFallback(raw, mappedModel, fallbackKey)
	if err != nil {
		return "", err
	}
	if string(rewritten) == string(raw) {
		return key, nil
	}
	var updated map[string]any
	if err := json.Unmarshal(rewritten, &updated); err != nil {
		return "", fmt.Errorf("unmarshal websocket payload after prompt cache key fallback: %w", err)
	}
	for name := range payload {
		delete(payload, name)
	}
	for name, value := range updated {
		payload[name] = value
	}
	return key, nil
}
